### PR TITLE
Cross-Distro support

### PR DESCRIPTION
**Pull request by mayormaynotbeano**
Added a rough outline of what cross distro support could look like. Not everyone uses APT or even Kali, so added options for Arch, Fedora etc.

Tested on:
Ubuntu 22.04 - APT (No issues)
Kali Linux - APT (No issues)
Arch Linux - Pacman (No issues)

If you have feedback, please feel free to give. Im still learning :)

### CODE REVIEW

**Comment by mayormaynotbeano** [comment]
How is it possible that these checks fail :'(

**Comment by gotr00t0day** [comment]
> Added a rough outline of what cross distro support could look like. Not everyone uses APT or even Kali, so added options for Arch, Fedora etc.
> 
> Tested on: Ubuntu 22.04 - APT (No issues) Kali Linux - APT (No issues) Arch Linux - Pacman (No issues)
> 
> If you have feedback, please feel free to give. Im still learning :)

Have you tested them on other distros? I want to make sure before merging.

**Comment by mayormaynotbeano** [comment]
> > Added a rough outline of what cross distro support could look like. Not everyone uses APT or even Kali, so added options for Arch, Fedora etc.
> > 
> > Tested on: Ubuntu 22.04 - APT (No issues) Kali Linux - APT (No issues) Arch Linux - Pacman (No issues)
> > 
> > If you have feedback, please feel free to give. Im still learning :)
> 
> Have you tested them on other distros? I want to make sure before merging.

So I have tested on the distro's I have listed. I can try them on fedora if you want, which would be dnf. Yum worked, zypper im not sure, but it is the correct package names.

**Comment by gotr00t0day** [comment]
> > > Added a rough outline of what cross distro support could look like. Not everyone uses APT or even Kali, so added options for Arch, Fedora etc.
> > > Tested on: Ubuntu 22.04 - APT (No issues) Kali Linux - APT (No issues) Arch Linux - Pacman (No issues)
> > > If you have feedback, please feel free to give. Im still learning :)
> > 
> > 
> > Have you tested them on other distros? I want to make sure before merging.
> 
> So I have tested on the distro's I have listed. I can try them on fedora if you want, which would be dnf. Yum worked, zypper im not sure, but it is the correct package names.

Ok cool

**Comment by mayormaynotbeano** [comment]
> > > > Added a rough outline of what cross distro support could look like. Not everyone uses APT or even Kali, so added options for Arch, Fedora etc.
> > > > Tested on: Ubuntu 22.04 - APT (No issues) Kali Linux - APT (No issues) Arch Linux - Pacman (No issues)
> > > > If you have feedback, please feel free to give. Im still learning :)
> > > 
> > > 
> > > Have you tested them on other distros? I want to make sure before merging.
> > 
> > So I have tested on the distro's I have listed. I can try them on fedora if you want, which would be dnf. Yum worked, zypper im not sure, but it is the correct package names.
> 
> Ok cool

So update, tonight i will check all the distro's, to see if they function well. Ill deliver a report on it.

**Comment by mayormaynotbeano** [comment]
I suggest not adding red hat, but this could be done in the future. The other ones function as expected in my testing enviroments. If you want to be really sure, you should test them yourself too :)

**Comment by mayormaynotbeano** [comment]
Hey! What's your thoughts on the pull. I tested and it works, so there should be no problems commuting to main.

**Pull request closed without merging**
